version: '3'

services:
  frontend:
    image: node:20-alpine
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "
        yarn &&
        yarn dev --host 0.0.0.0
      "

  backend:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "
        yarn &&
        yarn start:dev
      "

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data

  tbls:
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./:/work
    command: doc --force
    depends_on:
      - db